### ISSUE TITLE
Allow a different hostname other than quay.io

### ISSUE THREAD

**Issue by snoby** [koudaiii/qucli#22]
Looking at the code it seems that quay.io is hard coded.  We have a private enterprise version of quay.io and it would be great if I could change the default 'quay.io' to 'quay.example.com' or something like that.
Basically can you setup a config file or add in an extra option to point to a different hostname?  Thanks!

**Comment by koudaiii** [comment]
Oh, I didn't know [the enterprise version](https://coreos.com/quay-enterprise/) !! 
I will add `--hostname` option for enterprise version 👍

**Comment by snoby** [comment]
I hacked the code and put in my enterprise URL and everything worked perfectly!

**Comment by koudaiii** [comment]
Released v0.5.0 #26  

https://github.com/koudaiii/qucli/blob/7a6c1564430b79e90df1858366cf0f4a6d997086/README.md
 
> if Quay Enterprise user, add Enviroment QUAY_HOSTNAME or --hostname
> 
> ```shell-session
> $ export QUAY_HOSTNAME=quay.example.com
> $ qucli list koudaiii
> or
> $ qucli list koudaiii --hostname=quay.example.com
> ```

Thank you for great feedback 👍 👍
