### ISSUE TITLE
should the default hostname not be quay.io?

### ISSUE THREAD

**Issue by 030** [koudaiii/qucli#40]
I was trying to run the example, but it turned out the QUAY_HOSTNAME had to be set as well. I was assuming that the default would point to quay.io. What is your opinion about this?

I suggest to add `-e QUAY_HOSTNAME=quay.io` to the docker example. If this is omitted the following is returned on Windows:

```
err: Get https://some-number/api/v1/repository?namespace=some-namespace&public=true: dial tcp some-ip:443: getsockopt: connection refused
```

**Comment by koudaiii** [comment]
@030 Thank you for feedback 🙏 

> I suggest to add -e QUAY_HOSTNAME=quay.io to the docker example. If this is omitted the following is returned on Windows:

I'm bad 🤦‍♂
LGTM 👍 Can you send a Pull Request to update the [README](https://github.com/koudaiii/qucli/tree/73b63479e7763f160ef0ecd686d99b29570d48c3#run-in-a-docker-container)? 😄

**Comment by 030** [comment]
@koudaiii PR has been created

**Comment by koudaiii** [comment]
Thank you 😄 merged 👍

**Comment by koudaiii** [comment]
if run `qucli` in a container, `qucli` use `HOSTNAME` of a container. This is a bug of `qucli`.  `qucli` should use `https://quay,io/` in default(If you want to specify, use `--hostname` or  `QUAY_HOSTNAME`).

Fix https://github.com/koudaiii/qucli/releases/tag/v0.6.6
