### ISSUE TITLE
the command `list` doesn't work

### ISSUE THREAD

**Issue by mixua** [koudaiii/qucli#42]
I just found an issue, please fix it if it not so huge dial.
`docker run -t --rm -e quay.io -e $QUAY_API_TOKEN quay.io/koudaiii/qucli:latest list $QUAY_ORG --is-public=true`
> err: Get https://b1a1d6f3d652/api/v1/repository?namespace=QUAY_ORG&public=true: dial tcp 172.17.0.2:443: getsockopt: connection refused

**Comment by koudaiii** [comment]
Thank you for the feedback 👍 
Sorry, I’ll check it 🤔

**Comment by koudaiii** [comment]
if run `qucli` in a container, `qucli` use `HOSTNAME` of a container. This is a bug of `qucli`.  `qucli` should use `https://quay,io/` in default(If you want to specify, use `--hostname` or  `QUAY_HOSTNAME`).

Fix https://github.com/koudaiii/qucli/releases/tag/v0.6.6
